account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('register', views.user_register, name="register"),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate_account, name='activate_account'),
    
]

afrivent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings    
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('afriventapp.urls')),
    path('order/', include('order.urls')),
    path('accounts/reset', auth_views.PasswordResetView.as_view(
       template_name = 'account/password_reset_form.html', email_template_name = 'account/password_reset_email.html', subject_template_name = 'account/password_reset_subject.txt' ), 
    name = 'password_reset'
    ),
    path('accounts/reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name = 'account/password_reset_done.html'
        ), name = 'password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name = 'account/password_reset_confirm.html'),
    name = 'password_reset_confirm'),


    path('accounts/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
    name='password_reset_complete'), 

   path('accounts/settings/password/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html'),
    name='password_change'),

   path('accounts/settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
    template_name='account/password_change_done.html'),
    name='password_change_done'
    ),
    path('accounts/', include('account.urls')),


    # path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

afriventapp/urls.py
from django.urls import path
from . import views

app_name = 'afrivent'

urlpatterns = [
    path('', views.home, name="home"),
    path('all/events', views.all_events, name="all-events"),
    path('event-order/details/<int:eventId>', views.event_order_details, name='event-order-details'),
    path('edit/event/<event_slug>', views.eventUpdate, name='edit-event' ),
    path('event/<slug>', views.EventDetailView, name='event-detail'),
    path('profile/<pk>', views.userdashboard, name='user-profile'),
    path('create/event', views.createEventForm, name='create-event'),
    path('new/event/created', views.eventCreated, name='event-created'),
    path('search', views.search, name='search'),
    path('payout/<pk>', views.requestPayout, name='request-payout'),
    path('generate-ticket/<pk>', views.generateTicket, name='generate-ticket')


   
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('process', views.orderProcess, name="orderProcess"),
    path('process/confirm', views.orderConfimation, name="orderConfirmation"),
    path('payment/process', views.processPayment, name='process'),
    path('payment/confirm', views.confirmPayment, name='confirm-payment'),
    # path('ticketpage/', views.ticketPage, name='ticket-page')
]

afriventapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save, post_save, post_delete
from .utils import unique_slug_generator
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=500)
    phone_number = PhoneNumberField(blank=True, null=True)
    bio = models.TextField(max_length=1000, blank=True)
    bank_name = models.CharField(max_length=50)
    account_number = models.IntegerField()
    account_name = models.CharField(max_length=550)
    balance = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    verified_email = models.BooleanField(default= False)

    

    class Meta:
        verbose_name = _("UserProfile")
        verbose_name_plural = _("UserProfiles")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("afrivent:user-profile", kwargs={"pk": self.pk})






class Event(models.Model):
    event_name = models.CharField("Enter name for Event", max_length=500)
    creator = models.ForeignKey(UserProfile, related_name='events_created', on_delete=models.CASCADE)
    address = models.TextField(max_length=5000)
    event_image = models.ImageField(upload_to='images')
    description = models.TextField(max_length=50000)
    start_date = models.DateField(auto_now=False, auto_now_add=False, null= True)
    start_time = models.TimeField(auto_now=False, auto_now_add=False, null= True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null= True)
    end_time = models.TimeField(auto_now=False, auto_now_add=False, null= True)
    slug = models.SlugField(blank = True, null = True) 
    ticket_sales_end_date = models.DateField(auto_now=False, auto_now_add=False, null= True)

    


    class Meta:
        verbose_name = _("Event")
        verbose_name_plural = _("Events")

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse("afrivent:event-detail", kwargs={"slug": self.slug})



class EventTicket(models.Model):
    type = models.CharField("Enter a name for ticket", max_length=50)
    quantity = models.PositiveIntegerField(default = 1)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    event = models.ForeignKey(Event, on_delete=models.CASCADE,related_name='event_ticket')

    class Meta:
        verbose_name = _("EventTicket")
        verbose_name_plural = ("EventTickets")


    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse("EventTicket_detail", kwargs ={"pk": self.pk})




def event_pre_save(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(event_pre_save, sender=Event)

afriventapp/forms.py
from django import forms
from afriventapp.models import Event, EventTicket

# class CreateEven

class EventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields =  ('event_name', 'address', 'event_image', 'description', 
                'start_date', 'start_time' , 'end_date', 'end_time')

class TicketForm(forms.ModelForm):
    class Meta:
        model = EventTicket
        fields = ('type','quantity', 'amount')

afriventapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse, redirect
from .models import Event, EventTicket, UserProfile
from django.views.generic import ListView, DetailView
from django.db.models import Max, Min
from order.models import Order, OrderItem
import json
from django.http import JsonResponse
from django.http import HttpResponse
from afriventapp.forms import EventForm, TicketForm
from django.views.generic.edit import UpdateView
from django.core.paginator import Paginator
# from afriventapp.models import Event
from django.contrib.auth.models import User
from datetime import date
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from order.generate_barcode import barcodeGenerator
import base64
from django.core.files.base import ContentFile


def home(request):
    events = Event.objects.all()[:9]
    top_events = Event.objects.all()[:2]
    context = {
        'events': events,
        'top_events': top_events
        }
    return render(request, 'afriventapp/event_app/home.html', context)


# class EventDetailView(DetailView):
#     model = Event
#     template_name = "afriventapp/event-dashboard.html"
#     context_object_name = 'event'


#     def get_context_data(self, **kwargs):    from django.views.generic.edit import UpdateView


#         # Call the base implementation first to get a context
#         context = super().get_context_data(**kwargs)
#         # Add in a QuerySet of all the books
#         context['tickets'] = EventTicket.objects.filter()
#         return context


def all_events(request):
    event_list = Event.objects.all()
    paginator = Paginator(event_list, 6) # Show 25 contacts per page
    page = request.GET.get('page')
    events = paginator.get_page(page)
    return render(request, 'afriventapp/event_app/events.html', {'events': events})

    
    
def EventDetailView(request, slug):
    event =  get_object_or_404(Event, slug=slug)
    ticket = EventTicket.objects.filter(event=event)
    ticket_price_range = ticket.aggregate(min_price=Min('amount'), max_price=Max('amount'))
    events = Event.objects.all()[:9]
    context = {
        'event':event,
        'events':events,
        'tickets':ticket,
        'ticket_price_range': ticket_price_range
    }
    return render(request, 'afriventapp/event_app/single.html', context)

@login_required
def userdashboard(request, pk):
    # user = get_object_or_404(user)
    user = get_object_or_404(User, pk=pk)
    user_profile = get_object_or_404(UserProfile, user=pk)
    events = Event.objects.filter(creator = user_profile)
    orders = Order.objects.filter( user = user)
    # registeredOrders = Order.objects.filter(user =)
    tickets = OrderItem.objects.filter(user = user)
    print(request.user.username, user)
    context = {
        'user_profile':user_profile,
        'events':events,
        'orders':orders,
        'tickets': tickets,
        'user':user

    }
    return render(request, 'afriventapp/user-dashboard.html', context)

@login_required
def generateTicket(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order_items = OrderItem.objects.filter(order=order)
    reference_code = order.ref_code
    if order.payment_confirmation == True:
        barcode = barcodeGenerator(order.id, order.event, reference_code, order.order_unique_id, order.user)
        # format, imgstr = barcode.split(';base64,') 
        # print(barcode)
        # ext = format.split('/')[-1] 
        # barcode = ContentFile(base64.b64decode(imgstr), name='{}.'.format(order.id) + ext)


    else:
        return render(request, 'afriventapp/404.html', context={
            'order':order
        })
 
    context = {
        'order': order,
        'order_items' : order_items,
        'barcode':barcode
    }

    return render(request, 'order/ticket.html', context) 


def requestPayout(request, pk):
    user = get_object_or_404(User, pk=pk)
    user_profile = get_object_or_404(UserProfile, user=pk)
    #send_mail()`
    user_profile.balance -= user_profile.balance
    user_profile.save()
    context = {}
    return render(request, 'afriventapp/requestPayout.html', context)
    



def event_order_details(request, eventId):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    events = Event.objects.filter(creator = user_profile)
    if request.method == "GET":
        orderDetails = Order.objects.filter(event_id=eventId).exclude(payment_confirmation = False).values()
        # totalOrderPrice  = Order.objects.filter(event_id=eventId).values('total_cost')
    context = {
        'user_profile':user_profile,
        'orderDetails':orderDetails,

    }
    return JsonResponse(
        {'orderDetails':list(orderDetails)}
        # {'totalOrderPrice': sum(list(totalOrderPrice))}
        )

@login_required
def createEventForm(request):
    return render(request, 'afriventapp/create-event.html')


@login_required
def eventCreated(request):
    if request.method == 'POST':
        queryDict = request.POST
        
        ticketType = queryDict.getlist('type')
        ticketAmount = queryDict.getlist('amount')
        ticketQuantity = queryDict.getlist('quantity')
        print(queryDict)
        event_form = EventForm(request.POST, request.FILES)
        if event_form.is_valid():
            event = event_form.save(commit=False)
            user_profile = get_object_or_404(UserProfile, user=request.user)
            event.creator =  user_profile
            print('hi')
            event.save()
            ticket_form = TicketForm(request.POST)
            if ticket_form.is_valid():
                ticket_event = get_object_or_404(Event, pk=event.id)
                for ticket in range(len(ticketType)):
                    EventTicket.objects.create(
                        type = ticketType[ticket],
                        quantity = ticketQuantity[ticket],
                        amount = ticketAmount[ticket],
                        event = ticket_event
                    )
                    
            return HttpResponse(reverse('afrivent:event-detail', args=(event.slug,)))
            
    else:
        form = EventForm()
    
    return redirect('afrivent:event-detail', event.slug)



class EventUpdate(UpdateView):
    model = Event
    fields = '__all__'
    template_name = 'afriventapp/edit-event.html'

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}
        if self.object:
            context['ticket'] = EventTicket.objects.filter(event=self.object) 
            context_object_name = 'EventTicket'
            print(context_object_name)
        #     if context_object_name:
        #         context[context_object_name] = self.object
        # context.update(kwargs)
        return super().get_context_data(**context)

@login_required
def eventUpdate(request, event_slug):
    event_edit =  get_object_or_404(Event, slug=event_slug)
    ticketquery = EventTicket.objects.filter(event=event_edit)
    if request.method == 'POST':
        queryDict = request.POST
        ticketType = queryDict.getlist('type')
        ticketAmount = queryDict.getlist('amount')
        ticketQuantity = queryDict.getlist('quantity')
        event_form = EventForm(request.POST, request.FILES, instance = event_edit)
        if event_form.is_valid():
            event_form.save()
            ticketform = TicketForm(request.POST) 
            ticketquery.delete()
            for ticket in range(len(ticketType)):
                EventTicket.objects.create(
                        type = ticketType[ticket],
                        quantity = ticketQuantity[ticket],
                        amount = ticketAmount[ticket],
                        event = event_edit
                    )

            return redirect(reverse('afrivent:event-detail', args=(event_slug,)))
            
    else:
        event_form = EventForm()
        ticketform = TicketForm()

    context = {

        'event': event_edit,
        'ticket': ticketquery
    }
    return render(request, 'afriventapp/edit-event.html', context)


def search(request):
    try:
        if request.method == 'GET':
            query = request.GET['q']
            events = Event.objects.filter(Q(event_name__icontains = request.GET['q']) |
            Q(creator__user__username__icontains= request.GET['q']) | Q(description__icontains = request.GET['q']) )
        context = {'events':events, 'query':query}
        if events:
            
            print(events)            
            return render(request, 'afriventapp/search.html', context)
        else:
            return render(request, 'afriventapp/search.html')
    except MultiValueDictKeyError as e:
        print(e)
        return render(request, 'afriventapp/404.html')

afriventapp/templates/afriventapp/event_app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %} Afrivent Event App{% endblock %}</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,700,900|Oswald:400,700"
    />
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"> -->
    <link
      rel="stylesheet"
      href="{% static 'css/owl.theme.default.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}" />
    <link rel="stylesheet" href="{% static 'css/mediaelementplayer.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'fonts/flaticon/font/flaticon.css' %} "
    />
    <link rel="stylesheet" href="{% static 'css/fl-bigmug-line.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css"
      integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U="
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href=" {% static 'css/aos.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/styles.css' %}" />

    {% block stylesheet %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/event_style.css' %}" />
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="{% url 'afrivent:home' %}" class="text-white h2 mr-3"
          ><strong>AFRIVENT<span class="text-primary">.</span></strong></a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a
                class="nav-link text-white h4"
                href="{% url 'afrivent:all-events' %}"
                >Events</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link text-white h4"
                href="{% url 'afrivent:create-event' %}"
                >Create Event</a
              >
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white h4" href="{% url 'account:login' %}"
                >Sign In</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link text-white h4"
                href="{% url 'account:register' %}"
                >Sign Up</a
              >
            </li>

            {% endif %}
          </ul>
          <form
            class="form-inline my-2 my-lg-0"
            method="GET"
            action="{% url 'afrivent:search'%}"
          >
            <input
              class="form-control mr-sm-2"
              type="search"
              placeholder="Search"
              name="q"
              aria-label="Search"
            />
            <button class="btn my-2 my-sm-0" type="submit">Search</button>
          </form>
          {% if user.is_authenticated %}
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Howdy {{ user.username | title }}
          </a>
          <div
            class="dropdown-menu dropdown-menu-right"
            aria-labelledby="navbarDropdown"
          >
            <a
              class="dropdown-item"
              href="{% url 'afrivent:user-profile' user.id%}"
              >Your Dashboard</a
            >
            <a class="dropdown-item" href="{% url 'account:logout' %}"
              >Logout</a
            >
          </div>

          {% endif %}
        </div>
      </nav>
    </div>

    <!-- <div class="site-navbar mt-4">
        <div class="container py-1"> 
          <div class="row align-items-center">
            
            <div class="col-8 col-md-8 col-lg-4">
              <h1 class="mb-0"><a href="{% url 'afrivent:home' %}" class="text-white h2 mb-0"><strong>AFRIVENT<span class="text-primary">.</span></strong></a></h1>
            </div>
          
            <div class="col-4 col-md-4 col-lg-8">
              <nav class="site-navigation text-right text-md-right" role="navigation">

                <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a></div>

                <ul class="site-menu js-clone-nav d-none d-lg-block">
                  <li class="active">
                    <a href="index.html">Home</a>
                  </li>
                  <li><a href="{% url 'afrivent:all-events' %}">Events</a></li>
                  <li><a href="{% url 'afrivent:create-event' %}">Create Event</a></li>
                  <li><a href="#!">About</a></li>
                  {% if not user.is_authenticated %}
                  <li><a href="{% url 'account:login' %}">Sign In</a></li>
                  <li><a href="{% url 'account:register' %}">Sign Up</a></li>
                  {% else %}
                  <li class="has-children">
                    <a href="shows.html">Howdy {{ user.username | title }}</a>
                    <ul class="dropdown arrow-top">
                      <li><a href="{% url 'afrivent:user-profile' user.id%}">Your Dashboard</a></li>
                      <li><a href="{% url 'account:logout' %}">Logout</a></li>
                    </ul>
                  </li>
                  {% endif %}

                  
                </ul>
              </nav>
            </div>
           

          </div>
        </div>
      </div>
  </div>
    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
      </div>
    <div class="site-mobile-menu-body"></div>
  </div>  -->

    {% block content %} {% endblock %}

    <div class="bg-primary" data-aos="fade">
      <div class="container">
        <div class="row">
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-facebook text-white"></span
          ></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-twitter text-white"></span
          ></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-instagram text-white"></span
          ></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-linkedin text-white"></span
          ></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-pinterest text-white"></span
          ></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"
            ><span class="icon-youtube text-white"></span
          ></a>
        </div>
      </div>
    </div>

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="mb-5">
              <h3 class="footer-heading mb-4">About Afivent</h3>
              <p>Booking has never been more easier</p>
            </div>
          </div>
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <ul class="list-unstyled">
                <li><a href="#">Home</a></li>
                <li><a href="{% url 'afrivent:all-events' %}">Events</a></li>
                <li>
                  <a href="{% url 'afrivent:create-event' %}">Create Event</a>
                </li>
              </ul>
            </div>
          </div>

          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Follow Us</h3>

                <div>
                  <a href="#" class="pl-0 pr-3"
                    ><span class="icon-facebook"></span
                  ></a>
                  <a href="#" class="pl-3 pr-3"
                    ><span class="icon-twitter"></span
                  ></a>
                  <a href="#" class="pl-3 pr-3"
                    ><span class="icon-instagram"></span
                  ></a>
                  <a href="#" class="pl-3 pr-3"
                    ><span class="icon-linkedin"></span
                  ></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/event_main.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"
      integrity="sha256-yNbKY1y6h2rbVcQtf0b8lq4a+xpktyFc3pSYoGAY1qQ="
      crossorigin="anonymous"
    ></script>

    {% block script%}{% endblock %}
  </body>
</html>